### ISSUE TITLE
Eliminate fillArray for ObjObj Map by using FREE=null

### ISSUE THREAD

**Issue by frajt** [leventov/Koloboke#30]
Hi,

we are using Trove library with some extra modifications where one of them is about null reference being used for the FREE value. The initial array creation and rehashing do not require to fill the array with FREE values (one extra iteration over the complete array is now required).
Additionally it can be cheaper for a garbage collector to see a null reference than many references to a singleton object representing FREE - null should be for free.
Obviously there is some cost in handling key slots where the new NULL object represents null key - could be reduced by noNull case (like you do with noRemoved).

```java
protected static final Object REMOVED = new Object(), FREE = null, NULL = new Object();
```
Michal

**Comment by leventov** [comment]
This is implemented in [Koloboke Compile](https://koloboke.com/compile), it generates implementations that use `null` as the "free" value, if the implemented type is _not_ annotated with [`@NullKeyAllowed`](https://github.com/leventov/Koloboke/blob/master/compile/tutorial.md#allow-the-null-key).
