### ISSUE TITLE
putAll not overriden

### ISSUE THREAD

**Issue by MartinBurian** [leventov/Koloboke#56]
When generating implementation for

```
import com.koloboke.compile.KolobokeMap;

import javax.annotation.Nonnull;
import java.util.Map;

@KolobokeMap
public abstract class LongIntMap {
    public static KolobokeLongIntMap withExpectedSize(int n) {
        return new KolobokeLongIntMap(n);
    }

    public static KolobokeLongIntMap fromMap(Map<Long,Integer> map) {
        KolobokeLongIntMap m=new KolobokeLongIntMap(map.size());
        m.putAll(map);
        return m;
    }

    public abstract int get(long k);

    public abstract int put(long k, int v);

    public abstract int remove(long k);

    public abstract com.koloboke.collect.set.LongSet keySet();

    public abstract void putAll(@Nonnull Map<Long, Integer> m);

    public final int defaultValue() {
        return -1;
    }
}
```

Koloboke complains:
```
[ERROR] /.../LongIntMap.java:[33,26] Abstract method void putAll(java.util.Map<java.lang.Long,java.lang.Integer>); is not overridden in the generated Koloboke implementation class. Probably methods of such form are not supported for Map model with long key type and int value type
[ERROR] derived from method int put(long, int);.
[ERROR] Also probably one of the following (supported) methods was meant:
[ERROR] void putAll(@Nonnull
[ERROR] Map<? extends Long, ? extends Integer> m)
[ERROR] -> [Help 1]`
```

The signatures seem to be equivalent, am I doing something wrong?

Koloboke compile version 0.5.1 (from maven-central), OpenJDK 8, built using maven-compiler-plugin 3.6.1

(Also, just a quick question. Can I make the keySet() return a LongSet class generated in the same project?)

**Comment by leventov** [comment]
You could change your `putAll()` signature to accept `Map<? extends Long, ? extends Integer>`, it looks silly but should always work.

> Also, just a quick question. Can I make the keySet() return a LongSet class generated in the same project?

Map's keySet is not a generic Set implementation, it's a special _view_ implementation of Set, which delegates all methods to the parent Map implementation. `com.koloboke.collect.set.LongSet` which you already use is almost the most specific interface that you can use as `keySet()` return type. The most specific is [`HashLongSet`](http://leventov.github.io/Koloboke/api/1.0/java8/com/koloboke/collect/set/hash/HashLongSet.html). See [`@KolobokeMap`](http://leventov.github.io/Koloboke/compile/0.5/com/koloboke/compile/KolobokeMap.html) javadocs, find "keySet" on the page.

**Comment by MartinBurian** [comment]
It indeed worked, thanks for the advice and insights!
