### ISSUE TITLE
failed to build with error below

### ISSUE THREAD

**Issue by piaosama** [leventov/Koloboke#65]
try ro build the source for idea, when typed "**./gradlew buildMain -x test -x findbugsMain -x findbugsTest**"
 it said below: "
**/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/KolobokeMap.java:19: error: package com.koloboke.collect.hash does not exist
import com.koloboke.collect.hash.HashConfig;
                                ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/KolobokeMap.java:20: error: package com.koloboke.collect.map does not exist
import com.koloboke.collect.map.ObjIntMap;
                               ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/KolobokeMap.java:21: error: package com.koloboke.collect.map does not exist
import com.koloboke.collect.map.ObjIntMapFactory;
                               ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/KolobokeMap.java:22: error: package com.koloboke.collect.map.hash does not exist
import com.koloboke.collect.map.hash.*;
^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/KolobokeMap.java:23: error: package com.koloboke.collect.set.hash does not exist
import com.koloboke.collect.set.hash.HashLongSet;
                                    ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/KolobokeMap.java:24: error: package com.koloboke.collect.set.hash does not exist
import com.koloboke.collect.set.hash.HashObjSet;
                                    ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/KolobokeMap.java:25: error: package com.koloboke.function does not exist
import com.koloboke.function.BiConsumer;
                            ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/NullKeyAllowed.java:19: error: package com.koloboke.collect.hash does not exist
import com.koloboke.collect.hash.ObjHashFactory;
                                ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/CustomKeyEquivalence.java:19: error: package com.koloboke.collect does not exist
import com.koloboke.collect.Equivalence;
                           ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/CustomKeyEquivalence.java:20: error: package com.koloboke.collect.map does not exist
import com.koloboke.collect.map.ObjObjMap;
                               ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/CustomKeyEquivalence.java:21: error: package com.koloboke.collect.map.hash does not exist
import com.koloboke.collect.map.hash.HashObjObjMapFactory;
                                    ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/CustomKeyEquivalence.java:22: error: package com.koloboke.collect.set does not exist
import com.koloboke.collect.set.ObjSet;
                               ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/CustomKeyEquivalence.java:23: error: package com.koloboke.collect.set.hash does not exist
import com.koloboke.collect.set.hash.HashObjSetFactory;
                                    ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/ConcurrentModificationUnchecked.java:19: error: package com.koloboke.collect does not exist
import com.koloboke.collect.Cursor;
                           ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/KolobokeSet.java:19: error: package com.koloboke.collect.hash does not exist
import com.koloboke.collect.hash.HashConfig;
                                ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/KolobokeSet.java:20: error: package com.koloboke.collect.set.hash does not exist
import com.koloboke.collect.set.hash.HashIntSet;
                                    ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/KolobokeSet.java:21: error: package com.koloboke.collect.set.hash does not exist
import com.koloboke.collect.set.hash.HashObjSet;
                                    ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/KolobokeSet.java:22: error: package com.koloboke.function does not exist
import com.koloboke.function.Consumer;
                            ^
/home/piaopiao/Koloboke/compile/src/main/java/com/koloboke/compile/hash/algo/openaddressing/LinearProbing.java:19: error: package com.koloboke.collect.hash does not exist
import com.koloboke.collect.hash.HashConfig;
                                ^
19 errors
:compile:compileJava FAILED**
"
How to solve this?

**Comment by piaosama** [comment]
solved this

**Comment by Yangxiaohan0120** [comment]
Can you tell me how you solved it
